{% set name = "GES-comp-echem" %}
{% set version = "0.3.0" %}



package:
  name: "{{ name|lower }}"
  version: "{{ version }}"



source:
  url: https://github.com/GES-compchem/{{ name }}/archive/refs/tags/{{ version }}.zip

build:
  noarch: python
  number: 0



requirements:
  host:
    - python>=3.8
    - pip
    - setuptools
    - numpy
    - pandas>=1.3.0
    - sh
    - rdkit
    - morfeus-ml
    - matplotlib

  run:
    - python>=3.8
    - numpy
    - pandas>=1.3.0
    - sh
    - rdkit
    - morfeus-ml
    - matplotlib


about:
  home: The package home page
  license: UNKNOWN
  license_family: OTHER
  license_file:
  summary: ""
  doc_url:
  dev_url:



extra:
  recipe-maintainers:
    - GES-compchem
